### ISSUE TITLE
Node not working

### ISSUE THREAD

**Issue by AlexandreAlle** [IBMPredictiveAnalytics/Watson_Language_ID#1]
Node is not working.

API address seems to have changed ?
That's the one in the node:
https://gateway.watsonplatform.net/language-translation/api/v2/identify

That's the one I have on Bluemix:
https://gateway.watsonplatform.net/language-translator/api

Thanks

**Comment by Wenpei** [comment]
@AlexandreAlle Greg is not work on this now, If you have api username/password, can you help to fix this?
I can support you if you face any issues.

**Comment by Wenpei** [comment]
mail me if you have any thought  yuwenp@cn.ibm.com

**Comment by Wenpei** [comment]
Fix this issues in 1.0.1
